---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: voxcpm-space
spec:
  encryptedData:
    .dockerconfigjson: AgC1UtnY1aoHSM1dzhPbv/VsSYhPosFI5bvNIl+t3o1OxE0U56DyqJkESitzn7VL2P8PxvMQ0Kzoyqp52b71MDsrNi55IyG9UAy3rMlq4x8//gQVHuRim9I745zDU+tYnREKxXW7T5iGVftgL5ySToWkZlsMgAFBWR3DgsZpDs1LQh7XdkkgWEAHSeuZpJ1A3tsjRdnqX53QtYHgwaNZZVK3pDjXCiNFm+gM1eL2YQ1Zb/ArPOcqsE5VHYyn+wyqeqtOujdVuNYpWfysZazvjVRaxMskYn6Rb/rjtX8R29ANtk3FTCWgQ8iTAiWKkCGHyJ3XXOFQN49OnbFZytSI72JUUeYa7Et9n+K3b5TDD7Z7MMrlY50fKq3OA3PqMkr9qSx8uyvMebJKD6VcLtUl11A4lEhxyiseGAPwTFaYP4Zh8GqpF8bsncMx9KVLc28Hxar2ms0FYwGLuWXGQYzR+SI5vciAr93RdVSEE18yLv2g2mD9NfpW4OJng9ScXGM7pbQWwi3kpwU0YqEj/wG8LWjYBUUNgZIzpvBtnp8LDr/QlB5OZo1F9kC+ht3bz2yaeuvsUVeL/A1gHd190r/LHd/SM/KG6lcwRe0vIwMLluDfChh00ryC0NHmGNYVFXSJ/j3CSlUJexyB8kjD9+eVys7SAfx6E9eQTLgoO9cyY5OntrlpfCsngFkP55FQipEJpFl8MdR19cWXahqJFwzvIwYF7ejsE+FYmVw4l6eQp/kgBi4R1uiyZGfWGGCzzO8p5PBuRat2totG06tacCoyS0L/L7O8OVXcpLMfR11KHRIJGliffqOL9ujd6F93nfbxDf9enJsu5pOCjj8/r1WoZkfSUPnL7dZkM2DNcV4lnDUGmE5kB4ZP59fKdSIN671rBi6BfSna5lGwgam8kVJJT1RygHQOPHpl5zvOK4I3w/GMaYGoi2dzQ99WMyiIAIQ4MwHXRBhq+RTdy7iORvUI3fFIsMfeSn8SXw71jShbiCZWA/X/pFw+KCmQuvnPx8VpO9kTnEQpVB1ElGgQKWobzfac+ZGUdinhlCk/7QW4CWCxRbm1Eh42V/0iorjoAmYB3yVwGq7xefQBPIAiExPDSFyDynHCA+FFZ1ftAqup6bq+RY4V/oXZrrZFRVB857wGPAlhfUrz/rMOXZUzVB++sagsxiAqudy8wW2UX77z3+K8pX6lNpXimZFweoxVDcs6BUKOpi6PcizIWAq+iA==
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: voxcpm-space
    type: kubernetes.io/dockerconfigjson
