apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voxcpm-space-live
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: voxcpm-space-live-tls
      hosts:
        - voxcpm.space
        - www.voxcpm.space
  rules:
    - host: voxcpm.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voxcpm-space
                port:
                  number: 80
    - host: www.voxcpm.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voxcpm-space
                port:
                  number: 80
