apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress-live.yaml
  - ingress-preview.yaml
images:
  - name: registry.144.91.77.245.sslip.io/voxcpm-space
    newTag: e579cb6c491d7c48fb6d713b811fecf2e6c70641
