apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress-live.yaml
  - ingress-preview.yaml
images:
  - name: registry.144.91.77.245.sslip.io/voxcpm-space
    newTag: 8d625f090d1d55e04724befea5f118d7a3e44d6a
